[package]
name = "font-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
font-core = { path = "../font-core" }
lru = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
directories = "5.0.1"
parking_lot = "0.12.1"